### ISSUE TITLE
Tax Exchange Rate - source and target currency codes

### ISSUE THREAD

**Issue by vanjoechua** [klsheng/myinvois-php-sdk#1]
Hi,
First of all I want to thank you for this package. It is a god send! I noticed that the Source and Target currency codes for Tax Exchange Rate cant be set. Is it by design or just not implemented?

Sample UBL from LHDN site
```
<cac:TaxExchangeRate>
<cbc:SourceCurrencyCode>EUR</cbc:SourceCurrencyCode>
<cbc:TargetCurrencyCode>MRY</cbc:TargetCurrencyCode>
<cbc:CalculationRate>5.07</cbc:CalculationRate>
</cac:TaxExchangeRate>
```

**Comment by klsheng** [comment]
Missing from implementation. Thanks for informing.

If you found something is missing, you may inform me again.

**Comment by vanjoechua** [comment]
Thank you!

**Comment by klsheng** [comment]
Code updated to main branch and tagged as 1.0.5
