### ISSUE TITLE
how to use reject Document from customer side? 

### ISSUE THREAD

**Issue by toro88** [klsheng/myinvois-php-sdk#11]
$prodMode = false;
$client = new MyInvoisClient('client_id', 'client_secret', $prodMode);

$client->login();
$access_token = $client->getAccessToken();

$reason = 'Customer reject';
$response = $client->rejectDocument($id, $reason);

i got below error

array(2) {
  ["errorMessage"]=>
  array(1) {
    ["error"]=>
    array(4) {
      ["code"]=>
      string(12) "AccessDenied"
      ["message"]=>
      string(59) "The document cannot be cancelled or requested for rejection"
      ["target"]=>
      string(22) "Update Document Status"
      ["details"]=>
      array(1) {
        [0]=>
        array(3) {
          ["code"]=>
          string(9) "Forbidden"
          ["target"]=>
          string(13) "Document.UUID"
          ["message"]=>
          string(62) "It seems that you are not authorized to update document status"
        }
      }
    }
  }
  ["errorCode"]=>
  int(403)
}

**Comment by klsheng** [comment]
Hi,  I think it is related to the permission of your account, you may need to check with LHDN. I suggest login to MyInvois portal, and check your permission in your profile, or if it is your client's profile, request them to verify for you.

![image](https://github.com/user-attachments/assets/c0ca1a63-3844-4e0b-9711-52f40e02495f)

**Comment by toro88** [comment]
I found the problem already, have to use customer's client id and secret, but why? if supplier build a apps system, and customer want to reject document from apps, customer have to fill in their own client id and client secret...

**Comment by klsheng** [comment]
For this, I think may be you need to check with FB, they face same permission issue (probably not in cancel / reject document) but definitely same with your situation.

I think customer side has to add your company as Intermediary, then you may retry again see whether it helps.

**Comment by toro88** [comment]
Hi, Yes i tried either one

1) Customer using their own client id and client secret to submit (OK)
2) Customer using supplier's software to submit, so customer have to add supplier as Intermediary in myportal (OK)
