### ISSUE TITLE
Status Invalid When Submitting in XML

### ISSUE THREAD

**Issue by USCI-FaizalRezaEbil** [klsheng/myinvois-php-sdk#14]
Hi today when i want to submit i received status invalid, previous 2 month ago i try it is working. Now it become invalid.
![einvoice](https://github.com/user-attachments/assets/895fe9ed-2651-4da6-93a3-d4e6e8a392b2)

**Comment by klsheng** [comment]
Can you call get document detail API to check the error? My side is working
