### ISSUE TITLE
Digital Certificates

### ISSUE THREAD

**Issue by chaiwei** [klsheng/myinvois-php-sdk#16]
Hi,

For the digital certificate, are we restricted to certificates issued only by the following Malaysian Certificate Authorities (CAs)?
- Pos Digicert Sdn Bhd
- MSC Trustgate.Com Sdn Bhd
- TM Technology Services Sdn Bhd

Can we use certificates from other providers like RapidSSL or Comodo?

**Comment by klsheng** [comment]
Correct, you may refer https://www.mcmc.gov.my/en/sectors/digital-signature/list-of-licensees

**Comment by chaiwei** [comment]
Thank you
