### ISSUE TITLE
Document Signature Validator errors

### ISSUE THREAD

**Issue by vanjoechua** [klsheng/myinvois-php-sdk#5]
After using the signature branch and using a testing certificate from one of the authorized vendors I have encountered the following errors:

```
"errorCode":"DS320","error":"Signed properties digest value doesn't match digest calculated value from provided signed properties section where ID is id-xades-signed-props."

:"DS326","error":"Certificate X509IssuerName doesn't match the X509IssuerName value provided in the signed properties section."
```

Does anyone know what they mean. Is it caused by the certificate or am I am missing some information to include in the signature?

**Comment by klsheng** [comment]
After I get my test CA, I will continue to investigate on this. I believe is because of XXX = YYY, where there is space between =. In Myinvois gateway, they will treat this as error if referred from one of FB post comment.

**Comment by vanjoechua** [comment]
I switched the pattern of the Issuer Name to CN, OU, O then C and that seemed to take care of error DS326. Thanks to FB group comment.

Now only DS320 error left. I also saw comment in the FB group regarding:
_<ds:DigestMethod Algorithm="[http://www.w3.org/2001/04/xmlenc#sha256](https://www.w3.org/2001/04/xmlenc?fbclid=IwZXh0bgNhZW0CMTAAAR1xACAHKIr27S8o7g0b9ykvYwjjVY1WK-079uTaaLoT0QzDnDKx4h_g034_aem_4w0MPW28f8FpH1snw1wVNg#sha256)" xmlns:ds="[http://www.w3.org/2000/09/xmldsig](https://www.w3.org/2000/09/xmldsig?fbclid=IwZXh0bgNhZW0CMTAAAR0vVMOqJ0m_80dPcxnpqXPDoWrz_XNiqEH00tuXTPeUniVJlypxlKCY2Yo_aem_xFtqTHIC_mtxQ_8lrGIOsA)#" /> for the xml str you sha256 and base64, make sure you leave the space #" />. do not remove it when generating the digest_

**Comment by vanjoechua** [comment]
Got it to finally work..
```
$content = str_replace("<xades:SignedProperties Id=\"id-xades-signed-props\">", "<xades:SignedProperties Id=\"id-xades-signed-props\" xmlns:xades=\"http://uri.etsi.org/01903/v1.3.2#\">", $content);
        $content = str_replace("<ds:DigestMethod Algorithm=\"http://www.w3.org/2001/04/xmlenc#sha256\"></ds:DigestMethod>","<ds:DigestMethod Algorithm=\"http://www.w3.org/2001/04/xmlenc#sha256\" xmlns:ds=\"http://www.w3.org/2000/09/xmldsig#\"></ds:DigestMethod>", $content);
        $content = str_replace("<ds:X509SerialNumber>","<ds:X509SerialNumber xmlns:ds=\"http://www.w3.org/2000/09/xmldsig#\">", $content);
        $content = str_replace("<ds:X509IssuerName>","<ds:X509IssuerName xmlns:ds=\"http://www.w3.org/2000/09/xmldsig#\">", $content);
        $content = str_replace("<ds:DigestValue>","<ds:DigestValue xmlns:ds=\"http://www.w3.org/2000/09/xmldsig#\">", $content);
```

**Comment by klsheng** [comment]
Thanks for helping the community. I still waiting for test CA, once done. I will recheck this.

**Comment by vanjoechua** [comment]
Came back from long weekend and encountered DS333 error. Based on FB group comments I tried this:

AbstractDocumentBuilder

```
// Get original document and hash first before insert signature component
$documentString = $this->build();
// hash in bytes
$documentHash = MyInvoisHelper::getHash($documentString, true);

// $signature = $this->setSignatureValue($signature, $certPrivateKeyContent, $documentHash);

$signature = $this->setSignatureValue($signature, $certPrivateKeyContent, $documentString);
```

basically its the string that needs to be signed and not the hash. Hope this helps.

**Comment by klsheng** [comment]
Code updated as per comment. Now digital signature works in JSON and XML submission.

**Comment by vanjoechua** [comment]
Downloaded the latest version then encountered DS326 again. Switched OU and O and the error was cleared. It seems LHDN is very picky on the sequence.

**Comment by qusyairezwan** [comment]
> Downloaded the latest version then encountered DS326 again. Switched OU and O and the error was cleared. It seems LHDN is very picky on the sequence.

Thank you for heads up
I amend the AbstractDocumentBuilder.php

added this portion to solve the DS326 error and document valid in MyInvois portal now.

```
  $newOrderArray = [
            "CN" => $issuerArray["CN"],
            "OU" => $issuerArray["OU"],
            "O" => $issuerArray["O"],
            "C" => $issuerArray["C"]
        ];
```

**Comment by klsheng** [comment]
Thanks for the information. Let me amend when available.

**Comment by klsheng** [comment]
Code updated with 1.0.1 tag.

**Comment by NanYiNet** [comment]
I've had this problem too. Please tell me the solution, okay?
