### ISSUE TITLE
Invoice with more than 155 lines returns 403 with maintenance message

### ISSUE THREAD

**Issue by Edwin-Maya** [klsheng/myinvois-php-sdk#7]
Hello when i tried to upload a document with more than 155 invoice lines i receive a 403 message with this message:

![image](https://github.com/klsheng/myinvois-php-sdk/assets/39552052/9e3cb9cc-80a6-42a2-b451-f07e6a15b2bb)

anyone else encountering the same issue?

**Comment by klsheng** [comment]
I think MyInvois gateway is performing maintenance at that time.

FYI, you may need to follow the guideline from https://sdk.myinvois.hasil.gov.my/einvoicingapi/02-submit-documents/#additional-considerations
