### ISSUE TITLE
Issue with signature creation

### ISSUE THREAD

**Issue by syahmizul** [klsheng/myinvois-php-sdk#9]
Im using the latest version of your SDK,Im using the p12 cert and key provided from LHDN with the passphrase included,I get an error saying the issuername in signature properties is not the same

**Comment by syahmizul** [comment]
Sorry my dumbass didnt notice the existing pr regarding this issue,will close this one

**Comment by NanYiNet** [comment]
I've had this problem too. Please tell me the solution, okay?
